import assert from 'node:assert/strict';
import handler,{allowedAction} from './api/workspace.mjs';
const invoke=async(req)=>{const r={headers:{},setHeader(k,v){this.headers[k]=v},status(v){this.code=v;return this},json(v){this.body=v;return this},send(v){this.body=v;return this},end(){return this}};await handler(req,r);return r};
const request=(path,method='GET',body={})=>({url:path,query:{__path:path.slice(1)},method,headers:{},body});
let r=await invoke(request('/'));assert.equal(r.code,503);
Object.assign(process.env,{GTM_PUBLIC_ORIGIN:'https://test.vercel.app',GTM_CLOUD_PASSWORD:'test-password-only',GTM_CLOUD_CSRF:'test-csrf',GTM_WORKER_TOKEN:'test-worker-only',UPSTASH_REDIS_REST_URL:'https://redis.example',UPSTASH_REDIS_REST_TOKEN:'test-token'});
assert.equal((await invoke(request('/api/state'))).code,401);
assert.equal((await invoke(request('/api/worker','POST',{op:'poll'}))).code,401);
const auth='Basic '+Buffer.from('continere:test-password-only').toString('base64');
const authorized=(p,m,b)=>{const r=request(p,m,b);r.headers.authorization=auth;return r};
assert.equal((await invoke(authorized('/api/config','POST',{}))).code,403);
assert.equal((await invoke(authorized('/api/prospect/'+'a'.repeat(32)+'/send','POST',{}))).code,403);
assert.equal(allowedAction('/api/prospect/'+'a'.repeat(32)+'/send'),false);
assert.equal(allowedAction('/api/playbook/'+'a'.repeat(32)+'/approve'),true);
assert.equal((await invoke(authorized('/.env','GET'))).code,404);
let commands=[];
globalThis.fetch=async(url,options)=>{const cmd=JSON.parse(options.body);commands.push(cmd);return new Response(JSON.stringify({result:cmd[0]==='GET'?String(Date.now()):true}),{status:200})};
const post=authorized('/api/playbook/research','POST',{icp:'spa'});Object.assign(post.headers,{origin:process.env.GTM_PUBLIC_ORIGIN,'x-csrf-token':'test-csrf','content-type':'application/json'});
r=await invoke(post);assert.equal(r.code,202);assert.match(r.body.cloud_job,/^[a-f0-9-]{36}$/);assert.equal(commands.at(-1)[0],'EVAL');assert.ok(!commands.at(-1)[1].includes('LPOP'));
commands=[];const poll=request('/api/worker','POST',{op:'poll'});poll.headers.authorization='Bearer test-worker-only';await invoke(poll);assert.ok(commands[0][1].includes('LPOP'));assert.ok(!commands[0][1].includes('inflight'));
console.log('10 cloud access, approval and one-time delivery checks passed');

assert.equal(allowedAction('/api/crm/create'),true);
assert.equal(allowedAction('/api/crm/'+'a'.repeat(32)+'/approve'),true);
assert.equal(allowedAction('/api/crm/'+'a'.repeat(32)+'/send'),false);
assert.equal((await invoke(authorized('/api/crm/'+'a'.repeat(32)+'/send','POST',{}))).code,403);
console.log('CRM cloud preparation allowed; remote sending remains blocked');
